### ISSUE TITLE
Console spam with handshake error

### ISSUE THREAD

**Issue by SPAWNRYS-ban** [TCPShield/RealIP#103]
```
[05:02:53 ERROR]: Couldn't pass ProxyPingEvent to tcpshield
net.tcpshield.tcpshield.util.exception.manipulate.PlayerManipulationException: An exception occured during the handshake process
        at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:123) ~[?:?]
        at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.handleEvent(VelocityHandshakeHandler.java:68) ~[?:?]
        at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.onProxyPing(VelocityHandshakeHandler.java:62) ~[?:?]
        at net.tcpshield.tcpshield.velocity.handler.Lmbda$68.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-9450e660-b310)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set final com.velocitypowered.proxy.connection.MinecraftConnection field com.velocitypowered.proxy.connection.client.HandshakeSessionHandler$LegacyInboundConnection.connection to org.geysermc.geyser.platform.velocity.GeyserVelocityPingPassthrough$GeyserInboundConnection
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
        at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.getMinecraftConnection(VelocityPlayer.java:131) ~[?:?]
        at net.tcpshield.tcpshield.velocity.handler.VelocityPlayer.disconnect(VelocityPlayer.java:119) ~[?:?]
        ... 9 more
```

/velocity version
```
>....[05:06:38 INFO]: Velocity 3.3.0-SNAPSHOT (git-9450e660-b310)
[05:06:38 INFO]: Copyright 2018-2023 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[05:06:38 INFO]: velocitypowered.com - GitHub
```

**Comment by DylanKeir** [comment]
Disable MOTD & Ping Passthrough in your Geyser config.
