### ISSUE TITLE
Issue with Velocity

### ISSUE THREAD

**Issue by ghost** [TCPShield/RealIP#110]
I am setting up my minecraft network, but I am having issues with TCPShield's RealIP plugin.

When I try to connect to the server, it just says "Disconnected".
I've enabled debug mode, where I'm getting this error message:

```
[13:53:30 WARN] [net.tcpshield.tcpshield.velocity.TCPShieldVelocity]: Debug : Velocity: onHandshake Raw player hostname: beta.varovision.eu///176.121.56.116:5744///1723730010///MGUCMHMF0RVtiiObYeHVqRl0K33zl0ZkqdFXOHM4UgV6C/DMU6NqBjcB0t2LdRqfP20CvgIxALT8fF08UvG9CPfQB7W+Xv8Y6VcE9T4mi3+4U+Nxut73cL/f5CF9Foe/uIAZ7gb/5A==
[13:53:30 WARN] [net.tcpshield.tcpshield.velocity.TCPShieldVelocity]: Debug : Velocity: onPreLogin Raw player hostname: beta.varovision.eu
[13:53:30 WARN] [net.tcpshield.tcpshield.velocity.TCPShieldVelocity]: Debug : unknown[unknown/176.121.56.116] was disconnected because no proxy info was received and only-allow-proxy-connections is enabled. Raw payload = "beta.varovision.eu"
[13:53:30 ERROR]: net.tcpshield.tcpshield.util.exception.phase.HandshakeException: An exception occured during the handshake process
[13:53:30 ERROR]:       at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:164)
[13:53:30 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.handleEvent(VelocityHandshakeHandler.java:77)
[13:53:30 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.onPreLogin(VelocityHandshakeHandler.java:44)
[13:53:30 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.Lmbda$11.execute(Unknown Source)
[13:53:30 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[13:53:30 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[13:53:30 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[13:53:30 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:53:30 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:53:30 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[13:53:30 ERROR]: Caused by: net.tcpshield.tcpshield.util.exception.parse.InvalidPayloadException: length: 1, payload: [beta.varovision.eu], raw payload: beta.varovision.eu
[13:53:30 ERROR]:       at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:101)
[13:53:30 ERROR]:       ... 9 more
```

Please fix this :)
If it's a problem on my end, I'll be happy for even the slightest help :)

**Comment by negativems** [comment]
Hello, I have the same issue, I need to reconnect a lot times to my server to join.

The proxy (Velocity) does not says nothing until I enable debug.

![image](https://github.com/user-attachments/assets/494224b7-a725-490a-8743-79e40b9c19dc)

Specs:
Velocity 3.4.0-SNAPSHOT
RealIP: TCPShield-2.8.1
Ubuntu 22.04
Using Cloudflare DNS
