### ISSUE TITLE
TCPShield onPacketReceiving error

### ISSUE THREAD

**Issue by Nounejm** [TCPShield/RealIP#111]
Hey, I'm using Arclight for a hybrid minecraft server with plugins and mods. Not all the time but sometimes I'm getting this error when I refresh my server list page or whe I try to connect to the server.

`[17:23:12 ERROR] [Minecraft]: [TCPShield] Unhandled exception occurred in onPacketReceiving(PacketEvent) for TCPShield
java.lang.NoSuchMethodError: 'com.comphenix.protocol.injector.netty.Injector com.comphenix.protocol.injector.temporary.TemporaryPlayerFactory.getInjectorFromPlayer(org.bukkit.entity.Player)'
        at net.tcpshield.tcpshield.bukkit.protocollib.handler.ProtocolLibPlayer.setIP(ProtocolLibPlayer.java:74) ~[?:?]
        at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:148) ~[?:?]
        at net.tcpshield.tcpshield.bukkit.protocollib.handler.ProtocolLibHandshakeHandler.onPacketReceiving(ProtocolLibHandshakeHandler.java:28) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:122) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:75) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:555) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:519) ~[?:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:488) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.82.Final.jar%23115!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:95) ~[server-1.20.1-20230612.114412-srg.jar%23167!/:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.82.Final.jar%23117!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar%23119!/:4.1.82.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.82.Final.jar%23120!/:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%23116!/:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[17:23:12 ERROR] [Minecraft]: Parameters: 
  net.minecraft.network.protocol.handshake.ClientIntentionPacket@74beb786[
    f_134720_=763
    f_134721_=game.starcloudhosting.eu///127.0.0.1:25565///1724253792///MGUCMQCeKGx3C8qZFQmRFpz1+UOrmK83W55WGWxJGRoDCdBimP4BAFzv0Ba7ycYzX4vYkYACMFFq7JoOL3PUxuF5rNB94TBpsCrUTLFT6wmlOxqWT3A1DJK5treq8tzjVZ7JCP24Ng==
    f_134722_=25431
    f_134723_=STATUS
    fmlVersion=NONE
  ]`

**Comment by DylanKeir** [comment]
Which version of ProtocolLib and RealIP are you using?

**Comment by Nounejm** [comment]
I'm using ProtocolLib version 5.2.0 and TCPShield version 2.8.1.

**Comment by DylanKeir** [comment]
Can you try 2.8.0? https://github.com/TCPShield/RealIP/releases/tag/2.8.0

**Comment by Nounejm** [comment]
Got this error while using version 2.8.0.

`[22:12:30 ERROR] [Minecraft]: Error occurred while enabling TCPShield v2.8.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.Server.getMinecraftVersion()'
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:266) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460) ~[arclight-1.20.1-1.0.5-1a8925b.jar%23163!/:arclight-1.20.1-1.0.5-1a8925b]
        at net.minecraft.server.MinecraftServer.handler$zbb000$arclight$enablePlugins(MinecraftServerMixin.java:2137) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by DylanKeir** [comment]
Disable `prefer-protocollib`. I know, sounds insane. In your case it will still use ProtocolLib like it should, but it'll stop that error. It's because it tries to use a Paper method which doesn't exist in plain Spigot which you're using.

**Comment by Nounejm** [comment]
That fixed the enabeling error. I will message you if I get the packet error.

**Comment by Nounejm** [comment]
It has been a day without these errors so it has to be fixed. Thank you.
