### ISSUE TITLE
User not properly kicked out when directly connecting ([unknown/null] was disconnected because..)

### ISSUE THREAD

**Issue by reimertz** [TCPShield/RealIP#49]
It seems I am not properly disconnected when connecting directly to the server.

Server running latest Tuinity with ProtocolLib installed. 

Error:

```
WARN Debug : unknown[unknown/null] was disconnected because no proxy info was received and only-allow-proxy-connections is enabled. Raw payload = "XXXXXXX"
12.05 22:45:52 [Server] WARN net.tcpshield.tcpshield.util.exception.phase.HandshakeException: An exception occured during the handshake process
12.05 22:45:52 [Server] WARN at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:144)
12.05 22:45:52 [Server] WARN at net.tcpshield.tcpshield.bukkit.paper.handler.PaperHandshakeHandler.onHandshake(PaperHandshakeHandler.java:29)
12.05 22:45:52 [Server] WARN at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor59.execute(Unknown Source)
12.05 22:45:52 [Server] WARN at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
12.05 22:45:52 [Server] WARN at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
12.05 22:45:52 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
12.05 22:45:52 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
12.05 22:45:52 [Server] WARN at org.bukkit.event.Event.callEvent(Event.java:45)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.HandshakeListener.a(HandshakeListener.java:99)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:35)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:9)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:293)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.channelRead0(NetworkManager.java:282)
12.05 22:45:52 [Server] WARN at net.minecraft.server.v1_16_R3.NetworkManager.channelRead0(NetworkManager.java:50)
12.05 22:45:52 [Server] WARN at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:384)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.05 22:45:52 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
12.05 22:45:52 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
12.05 22:45:52 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
12.05 22:45:52 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

**Comment by DylanKeir** [comment]
TCPShield by default blocks all connections not originating from TCPShield proxies. If you would like to have this supported for yourself, you should whitelist your IP address in the `ip-whitelist` folder of the TCPShield plugin files. Just note, you should not be allowing players to connect using your backend IP as this completely negates the purpose of TCPShield.
