### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by SzinDzeks** [TCPShield/RealIP#57]

**Comment by Dogocoton** [comment]
It would be useful if it gets updated to 1.17, currently i'm using a trick: Running a Velocity proxy for only one server

**Comment by SzinDzeks** [comment]
> 
> 
> It would be useful if it gets updated to 1.17, currently i'm using a trick: Running a Velocity proxy for only one server

Decided to use the same trick. Using proxy comes with an added benefit of higher packet compression, which improves gameplay for players with slow internet connections.

**Comment by uranderu** [comment]
I would also like to see this, 1.17 is out for almost two months now :P

**Comment by trev-sharp** [comment]
Support for 1.17 is planned. Are there any specific errors occurring while enabling TCPShield? If so, please send them in this thread so I can take a look.

**Comment by uranderu** [comment]
@xPlumpOrange I get this when starting my server. What is weird though is that I also get errors for protocollib even though I updated to the latest version. But that is after these errors.
```
[21:37:20] [Server thread/ERROR]: Could not load 'plugins/TCPShield-2.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[patched_1.17.1.jar:git-Paper-127]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.17.1.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:402) ~[patched_1.17.1.jar:git-Paper-127]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[patched_1.17.1.jar:git-Paper-127]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-127]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-127]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:240) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[patched_1.17.1.jar:git-Paper-127]
	... 6 more
```

**Comment by trev-sharp** [comment]
> @xPlumpOrange I get this when starting my server. What is weird though is that I also get errors for protocollib even though I

Looks like Bukkit 1.17 now requires the `description` option in plugin.yml's. I'll get a pull request made with the fix. Thank you for sharing your error.

**Comment by DylanKeir** [comment]
Seems to be sorted as of the 2.5.4 release, thanks guys.
