### ISSUE TITLE
Error occurred while enabling TCPShield v2.5 (Is it up to date?)

### ISSUE THREAD

**Issue by 8PotatoChip8** [TCPShield/RealIP#62]
`[SEVERE] Error occurred while enabling TCPShield v2.5 (Is it up to date?): com/comphenix/protocol/events/PacketListener
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:40)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:176)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:159)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)`

Running Craftbukkit `craftbukkit-1.0.0-SNAPSHOT`

**Comment by trev-sharp** [comment]
It looks like you don't have the proper ProtocolLib installed on the server. Update/install the ProtocolLib plugin to the latest version and restart.

**Comment by 8PotatoChip8** [comment]
I already have the latest version of ProtocolLib on the server. As here is the full log https://paste.ubuntu.com/p/KsjmK7PrrM/

**Comment by trev-sharp** [comment]
> I already have the latest version of ProtocolLib on the server. As here is the full log https://paste.ubuntu.com/p/KsjmK7PrrM/

ProtocolLib failed to initiate, as shown above the TCPShield error. Either the version of ProtocolLib you are using is outdated or doesn't support your server.
