### ISSUE TITLE
Error occurred while enabling TCPShield v2.5 (Is it up to date?)

### ISSUE THREAD

**Issue by 8PotatoChip8** [TCPShield/RealIP#66]
`[SEVERE] Error occurred while enabling TCPShield v2.5 (Is it up to date?): net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.getLogger()Ljava/util/logging/Logger;
java.lang.AbstractMethodError: net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.getLogger()Ljava/util/logging/Logger;
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:36)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:176)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:159)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)`

Running Craftbukkit `craftbukkit-1.0.0-SNAPSHOT`

**Comment by DylanKeir** [comment]
Try using this version: https://github.com/TCPShield/RealIP/releases/tag/2.5.2

**Comment by 8PotatoChip8** [comment]
`[SEVERE] Could not load 'plugins\TCPShield-2.5.2.jar' in folder 'plugins':
java.lang.UnsupportedClassVersionError: net/tcpshield/tcpshield/bukkit/TCPShieldBukkit has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:170)
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:215)
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:141)
        at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:117)
        at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:52)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:141)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)`

This is the error using version 2.5.2

**Comment by DylanKeir** [comment]
You're using JDK 8, the plugin does not support below JDK 11.

**Comment by 8PotatoChip8** [comment]
You were correct. But here is new problem:

`[SEVERE] Error occurred while enabling TCPShield v2.5.2 (Is it up to date?): Method net/tcpshield/tcpshield/bukkit/TCPShieldBukkit.getLogger()Ljava/util/logging/Logger; is abstract
java.lang.AbstractMethodError: Method net/tcpshield/tcpshield/bukkit/TCPShieldBukkit.getLogger()Ljava/util/logging/Logger; is abstract
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.getLogger(TCPShieldBukkit.java)
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:36)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:176)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:159)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:337)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:324)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:161)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:388)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)`

**Comment by DylanKeir** [comment]
Which Spigot fork are you running and which version? It looks like an issue within your Spigot but I can take a look for you.

**Comment by 8PotatoChip8** [comment]
Running Craftbukkit `craftbukkit-1.0.0-SNAPSHOT`

**Comment by DylanKeir** [comment]
Eh? 1.0.0 as in Minecraft 1.0...? I don't think you're getting the right version, run the `version` command in your servers console.

**Comment by 8PotatoChip8** [comment]
no, uh yeah..... Minecraft 1.0 is correct

**Comment by DylanKeir** [comment]
Completely irrelevant but can I ask why you're running on such an old version? I've not heard of anybody running below 1.4.6 even with modpacks in years.

**Comment by 8PotatoChip8** [comment]
I am looking to run a Minecraft server "NostalgiaCraft" where we will run on the oldest version of Minecraft that has plugin capabilities.

**Comment by DylanKeir** [comment]
I'll be completely honest with you, this is such a tiny niche edge case which really shouldn't be supported in the plugin, your best option would be to modify your spigot to have a default implementation of JavaPlugin#getLogger (this is the issue, older versions of minecraft do not have a default logger), however chances are if this is an issue, many other things maybe as well so we cannot guarantee if you do fix that one issue that the plugin will even begin to function.

**Comment by DylanKeir** [comment]
Also, Steven has just informed me our proxies don't support any versions below 1.7, so regardless if you get the plugin to load, TCPShield can't protect you.

**Comment by 8PotatoChip8** [comment]
Oh, thats a disappointment. But alright. Thanks for helping me.
