### ISSUE TITLE
Error loading plugin TCPShield (WaterFall)

### ISSUE THREAD

**Issue by Menacho15** [TCPShield/RealIP#67]
`[17:31:26 WARN]: Error loading plugin TCPShield
java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=net/tcpshield/tcpshield/bungee/TCPShieldBungee, offset=6
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_292-ea]
at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:396) ~[?:1.8.0_292-ea]
at java.lang.ClassLoader.defineClass(ClassLoader.java:357) ~[?:1.8.0_292-ea]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_292-ea]
at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:951) ~[?:1.8.0_292-ea]
at java.lang.ClassLoader.loadClass(ClassLoader.java:896) ~[?:1.8.0_292-ea]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at java.lang.ClassLoader.loadClass(ClassLoader.java:879) ~[?:1.8.0_292-ea]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:394) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[proxy.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]`

**Comment by DylanKeir** [comment]
Which java version are you using? Release version 2.5.2 only support JDK11+.

**Comment by Menacho15** [comment]
Thats why it didn't work, my Java version is 8
