### ISSUE TITLE
Fix erroring on java version 17-ea

### ISSUE THREAD

**Issue by chezzzer** [TCPShield/RealIP#71]
Pretty sure the plugin is trying to parse 17-ea as a number. Take a look:

```
[14:07:32 ERROR]: Error occurred while enabling TCPShield v2.5.3 (Is it up to date?)
net.tcpshield.tcpshield.util.exception.phase.InitializationException: An exception occured during the initalization process
at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:47) ~[TCPShield-2.5.3 (2).jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-257]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-257]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-257]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-257]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-257]
at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-257]
at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-257]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-257]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-257]
at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "17-ea"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
at net.tcpshield.tcpshield.TCPShieldPlugin.initialization(TCPShieldPlugin.java:46) ~[TCPShield-2.5.3 (2).jar:?]
at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:45) ~[TCPShield-2.5.3 (2).jar:?]
... 10 more
```

**Comment by DylanKeir** [comment]
Hi, I've pushed a commit that would stop the plugin hard erroring. However, it does seem like you're using an early access version of java 17, so upgrading to the release version would fix your issue here.
