### ISSUE TITLE
Does not connecting to velocity

### ISSUE THREAD

**Issue by NONPLAYT** [TCPShield/RealIP#78]
Im trying connect to velocity, but get "Disconnecting"
I enabled debug mode and get this:

```
[22:59:39 WARN] [net.tcpshield.tcpshield.velocity.TCPShieldVelocity]: Debug : unknown[unknown/ip] was disconnected because no proxy info was received and only-allow-proxy-connections is enabled. Raw payload = "SERVER IP"
[22:59:39 ERROR]: net.tcpshield.tcpshield.util.exception.phase.HandshakeException: An exception occured during the handshake process
[22:59:39 ERROR]:       at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:163)
[22:59:39 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.handleEvent(VelocityHandshakeHandler.java:56)
[22:59:39 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.VelocityHandshakeHandler.onProxyPing(VelocityHandshakeHandler.java:41)
[22:59:39 ERROR]:       at net.tcpshield.tcpshield.velocity.handler.Lmbda$45.execute(Unknown Source)
[22:59:39 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47)
[22:59:39 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598)
[22:59:39 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479)
[22:59:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[22:59:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[22:59:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[22:59:39 ERROR]: Caused by: net.tcpshield.tcpshield.util.exception.parse.InvalidPayloadException: length: 1, payload: [SERVER IP], raw payload: SERVER IP
[22:59:39 ERROR]:       at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:100)
[22:59:39 ERROR]:       ... 9 more
```

**Comment by DylanKeir** [comment]
You seem to be trying to directly connect with `only-allow-proxy-connections` enabled.

**Comment by NONPLAYT** [comment]
> You seem to be trying to directly connect with `only-allow-proxy-connections` enabled.

I fixed this, I writes on discord support server and I forget to close issue) Sorry!
