### ISSUE TITLE
TCPShield ProtocolLib Error

### ISSUE THREAD

**Issue by anzenchitai** [TCPShield/RealIP#85]
Spigot version: 1.8.8
TCPShield version: 2.6.0
ProtocolLib version: 4.8.0

`[06:13:11] [Netty Epoll Server IO #1/ERROR]: [TCPShield] Unhandled exception occured in onPacketReceiving(PacketEvent) for TCPShield
java.lang.NoClassDefFoundError: com/comphenix/protocol/injector/temporary/TemporaryPlayerFactory
	at net.tcpshield.tcpshield.bukkit.protocollib.handler.ProtocolLibPlayer.setIP(ProtocolLibPlayer.java:74) ~[TCPShield-2.6.0.jar:?]
	at net.tcpshield.tcpshield.TCPShieldPacketHandler.handleHandshake(TCPShieldPacketHandler.java:147) ~[TCPShield-2.6.0.jar:?]
	at net.tcpshield.tcpshield.bukkit.protocollib.handler.ProtocolLibHandshakeHandler.onPacketReceiving(ProtocolLibHandshakeHandler.java:28) ~[TCPShield-2.6.0.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:360) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:325) [ProtocolLib.jar:4.8.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:600) [ProtocolLib.jar:4.8.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292) [ProtocolLib.jar:4.8.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.LegacyPingHandler.channelRead(SourceFile:94) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]`

**Comment by DylanKeir** [comment]
As the release notes state, if you're not on 1.19 you should be using TCPShield 2.5.6.

Release notes: https://github.com/TCPShield/RealIP/releases/tag/2.6.0
